const numbers = [
  { val: 0, ar: "٠", ar_long: "صفر", en: "Zero", transliteration: "sifr", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 1, ar: "١", ar_long: "واحد", en: "One", transliteration: "wahed", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 2, ar: "٢", ar_long: "اتنين", en: "Two", transliteration: "itneen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 3, ar: "٣", ar_long: "تلاتة", en: "Three", transliteration: "talata", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 4, ar: "٤", ar_long: "أربعة", en: "Four", transliteration: "arba'a", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 5, ar: "٥", ar_long: "خمسة", en: "Five", transliteration: "khamsa", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 6, ar: "٦", ar_long: "ستة", en: "Six", transliteration: "sitta", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 7, ar: "٧", ar_long: "سبعة", en: "Seven", transliteration: "saba'a", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 8, ar: "٨", ar_long: "تمنية", en: "Eight", transliteration: "tamanya", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 9, ar: "٩", ar_long: "تسعة", en: "Nine", transliteration: "tes'a", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 10, ar: "١٠", ar_long: "عشرة", en: "Ten", transliteration: "ashara", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 11, ar: "١١", ar_long: "أحد عشر", en: "Eleven", transliteration: "ahad 'ashar", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 12, ar: "١٢", ar_long: "اتنا عشر", en: "Twelve", transliteration: "itna 'ashar", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 13, ar: "١٣", ar_long: "تلاتا عشر", en: "Thirteen", transliteration: "talata 'ashar", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 14, ar: "١٤", ar_long: "أربعة عشر", en: "Fourteen", transliteration: "arba'a 'ashar", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 15, ar: "١٥", ar_long: "خمسة عشر", en: "Fifteen", transliteration: "khamsa 'ashar", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 16, ar: "١٦", ar_long: "ستة عشر", en: "Sixteen", transliteration: "sitta 'ashar", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 17, ar: "١٧", ar_long: "سبعة عشر", en: "Seventeen", transliteration: "saba'a 'ashar", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 18, ar: "١٨", ar_long: "تمنية عشر", en: "Eighteen", transliteration: "tamanya 'ashar", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 19, ar: "١٩", ar_long: "تسعة عشر", en: "Nineteen", transliteration: "tes'a 'ashar", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 20, ar: "٢٠", ar_long: "عشرين", en: "Twenty", transliteration: "ishreen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 21, ar: "٢١", ar_long: "واحد وعشرين", en: "Twenty-One", transliteration: "wahed w'ishreen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 22, ar: "٢٢", ar_long: "اتنين وعشرين", en: "Twenty-Two", transliteration: "itneen w'ishreen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 23, ar: "٢٣", ar_long: "تلاتة وعشرين", en: "Twenty-Three", transliteration: "talata w'ishreen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 24, ar: "٢٤", ar_long: "أربعة وعشرين", en: "Twenty-Four", transliteration: "arba'a w'ishreen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 25, ar: "٢٥", ar_long: "خمسة وعشرين", en: "Twenty-Five", transliteration: "khamsa w'ishreen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 26, ar: "٢٦", ar_long: "ستة وعشرين", en: "Twenty-Six", transliteration: "sitta w'ishreen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 27, ar: "٢٧", ar_long: "سبعة وعشرين", en: "Twenty-Seven", transliteration: "saba'a w'ishreen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 28, ar: "٢٨", ar_long: "تمنية وعشرين", en: "Twenty-Eight", transliteration: "tamanya w'ishreen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 29, ar: "٢٩", ar_long: "تسعة وعشرين", en: "Twenty-Nine", transliteration: "tes'a w'ishreen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 30, ar: "٣٠", ar_long: "تلاتين", en: "Thirty", transliteration: "talateen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 31, ar: "٣١", ar_long: "واحد وتلاتين", en: "Thirty-One", transliteration: "wahed w'talateen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 32, ar: "٣٢", ar_long: "اتنين وتلاتين", en: "Thirty-Two", transliteration: "itneen w'talateen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 33, ar: "٣٣", ar_long: "تلاتة وتلاتين", en: "Thirty-Three", transliteration: "talata w'talateen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 34, ar: "٣٤", ar_long: "أربعة وتلاتين", en: "Thirty-Four", transliteration: "arba'a w'talateen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 35, ar: "٣٥", ar_long: "خمسة وتلاتين", en: "Thirty-Five", transliteration: "khamsa w'talateen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 36, ar: "٣٦", ar_long: "ستة وتلاتين", en: "Thirty-Six", transliteration: "sitta w'talateen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 37, ar: "٣٧", ar_long: "سبعة وتلاتين", en: "Thirty-Seven", transliteration: "saba'a w'talateen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 38, ar: "٣٨", ar_long: "تمنية وتلاتين", en: "Thirty-Eight", transliteration: "tamanya w'talateen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 39, ar: "٣٩", ar_long: "تسعة وتلاتين", en: "Thirty-Nine", transliteration: "tes'a w'talateen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 40, ar: "٤٠", ar_long: "أربعين", en: "Forty", transliteration: "arba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 41, ar: "٤١", ar_long: "واحد وأربعين", en: "Forty-One", transliteration: "wahed w'arba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 42, ar: "٤٢", ar_long: "اتنين وأربعين", en: "Forty-Two", transliteration: "itneen w'arba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 43, ar: "٤٣", ar_long: "تلاتة وأربعين", en: "Forty-Three", transliteration: "talata w'arba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 44, ar: "٤٤", ar_long: "أربعة وأربعين", en: "Forty-Four", transliteration: "arba'a w'arba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 45, ar: "٤٥", ar_long: "خمسة وأربعين", en: "Forty-Five", transliteration: "khamsa w'arba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 46, ar: "٤٦", ar_long: "ستة وأربعين", en: "Forty-Six", transliteration: "sitta w'arba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 47, ar: "٤٧", ar_long: "سبعة وأربعين", en: "Forty-Seven", transliteration: "saba'a w'arba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 48, ar: "٤٨", ar_long: "تمنية وأربعين", en: "Forty-Eight", transliteration: "tamanya w'arba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 49, ar: "٤٩", ar_long: "تسعة وأربعين", en: "Forty-Nine", transliteration: "tes'a w'arba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 50, ar: "٥٠", ar_long: "خمسين", en: "Fifty", transliteration: "khamsin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 51, ar: "٥١", ar_long: "واحد وخمسين", en: "Fifty-One", transliteration: "wahed w'khamsin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 52, ar: "٥٢", ar_long: "اتنين وخمسين", en: "Fifty-Two", transliteration: "itneen w'khamsin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 53, ar: "٥٣", ar_long: "تلاتة وخمسين", en: "Fifty-Three", transliteration: "talata w'khamsin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 54, ar: "٥٤", ar_long: "أربعة وخمسين", en: "Fifty-Four", transliteration: "arba'a w'khamsin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 55, ar: "٥٥", ar_long: "خمسة وخمسين", en: "Fifty-Five", transliteration: "khamsa w'khamsin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 56, ar: "٥٦", ar_long: "ستة وخمسين", en: "Fifty-Six", transliteration: "sitta w'khamsin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 57, ar: "٥٧", ar_long: "سبعة وخمسين", en: "Fifty-Seven", transliteration: "saba'a w'khamsin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 58, ar: "٥٨", ar_long: "تمنية وخمسين", en: "Fifty-Eight", transliteration: "tamanya w'khamsin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 59, ar: "٥٩", ar_long: "تسعة وخمسين", en: "Fifty-Nine", transliteration: "tes'a w'khamsin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 60, ar: "٦٠", ar_long: "ستين", en: "Sixty", transliteration: "sittin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 61, ar: "٦١", ar_long: "واحد وستين", en: "Sixty-One", transliteration: "wahed w'sittin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 62, ar: "٦٢", ar_long: "اتنين وستين", en: "Sixty-Two", transliteration: "itneen w'sittin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 63, ar: "٦٣", ar_long: "تلاتة وستين", en: "Sixty-Three", transliteration: "talata w'sittin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 64, ar: "٦٤", ar_long: "أربعة وستين", en: "Sixty-Four", transliteration: "arba'a w'sittin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 65, ar: "٦٥", ar_long: "خمسة وستين", en: "Sixty-Five", transliteration: "khamsa w'sittin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 66, ar: "٦٦", ar_long: "ستة وستين", en: "Sixty-Six", transliteration: "sitta w'sittin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 67, ar: "٦٧", ar_long: "سبعة وستين", en: "Sixty-Seven", transliteration: "saba'a w'sittin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 68, ar: "٦٨", ar_long: "تمنية وستين", en: "Sixty-Eight", transliteration: "tamanya w'sittin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 69, ar: "٦٩", ar_long: "تسعة وستين", en: "Sixty-Nine", transliteration: "tes'a w'sittin", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 70, ar: "٧٠", ar_long: "سبعين", en: "Seventy", transliteration: "saba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 71, ar: "٧١", ar_long: "واحد وسبعين", en: "Seventy-One", transliteration: "wahed w'saba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 72, ar: "٧٢", ar_long: "اتنين وسبعين", en: "Seventy-Two", transliteration: "itneen w'saba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 73, ar: "٧٣", ar_long: "تلاتة وسبعين", en: "Seventy-Three", transliteration: "talata w'saba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 74, ar: "٧٤", ar_long: "أربعة وسبعين", en: "Seventy-Four", transliteration: "arba'a w'saba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 75, ar: "٧٥", ar_long: "خمسة وسبعين", en: "Seventy-Five", transliteration: "khamsa w'saba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 76, ar: "٧٦", ar_long: "ستة وسبعين", en: "Seventy-Six", transliteration: "sitta w'saba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 77, ar: "٧٧", ar_long: "سبعة وسبعين", en: "Seventy-Seven", transliteration: "saba'a w'saba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 78, ar: "٧٨", ar_long: "تمنية وسبعين", en: "Seventy-Eight", transliteration: "tamanya w'saba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 79, ar: "٧٩", ar_long: "تسعة وسبعين", en: "Seventy-Nine", transliteration: "tes'a w'saba'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 80, ar: "٨٠", ar_long: "تمانين", en: "Eighty", transliteration: "tamaneen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 81, ar: "٨١", ar_long: "واحد وتمانين", en: "Eighty-One", transliteration: "wahed w'tamaneen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 82, ar: "٨٢", ar_long: "اتنين وتمانين", en: "Eighty-Two", transliteration: "itneen w'tamaneen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 83, ar: "٨٣", ar_long: "تلاتة وتمانين", en: "Eighty-Three", transliteration: "talata w'tamaneen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 84, ar: "٨٤", ar_long: "أربعة وتمانين", en: "Eighty-Four", transliteration: "arba'a w'tamaneen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 85, ar: "٨٥", ar_long: "خمسة وتمانين", en: "Eighty-Five", transliteration: "khamsa w'tamaneen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 86, ar: "٨٦", ar_long: "ستة وتمانين", en: "Eighty-Six", transliteration: "sitta w'tamaneen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 87, ar: "٨٧", ar_long: "سبعة وتمانين", en: "Eighty-Seven", transliteration: "saba'a w'tamaneen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 88, ar: "٨٨", ar_long: "تمنية وتمانين", en: "Eighty-Eight", transliteration: "tamanya w'tamaneen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 89, ar: "٨٩", ar_long: "تسعة وتمانين", en: "Eighty-Nine", transliteration: "tes'a w'tamaneen", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 90, ar: "٩٠", ar_long: "تسعين", en: "Ninety", transliteration: "tes'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 91, ar: "٩١", ar_long: "واحد وتسعين", en: "Ninety-One", transliteration: "wahed w'tes'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 92, ar: "٩٢", ar_long: "اتنين وتسعين", en: "Ninety-Two", transliteration: "itneen w'tes'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 93, ar: "٩٣", ar_long: "تلاتة وتسعين", en: "Ninety-Three", transliteration: "talata w'tes'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 94, ar: "٩٤", ar_long: "أربعة وتسعين", en: "Ninety-Four", transliteration: "arba'a w'tes'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 95, ar: "٩٥", ar_long: "خمسة وتسعين", en: "Ninety-Five", transliteration: "khamsa w'tes'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 96, ar: "٩٦", ar_long: "ستة وتسعين", en: "Ninety-Six", transliteration: "sitta w'tes'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 97, ar: "٩٧", ar_long: "سبعة وتسعين", en: "Ninety-Seven", transliteration: "saba'a w'tes'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 98, ar: "٩٨", ar_long: "تمنية وتسعين", en: "Ninety-Eight", transliteration: "tamanya w'tes'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 99, ar: "٩٩", ar_long: "تسعة وتسعين", en: "Ninety-Nine", transliteration: "tes'a w'tes'een", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
  { val: 100, ar: "١٠٠", ar_long: "مئة", en: "Hundred", transliteration: "mi'a", level: 0, sr: { interval: 1, repetitions: 0, dueAt: null } },
];

export default numbers;
